# Changes here will be overwritten by Copier
_commit: 5.4.0
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: thomas.kane@diamond.ac.uk
author_name: Thomas Kane
component_lifecycle: experimental
component_owner: group:default/beamline-controls
component_type: service
description: FastCS support for XIMC motion controllers
distribution_name: fastcs-ximc
docker: true
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: fastcs_ximc
pypi: false
repo_name: fastcs-ximc
strict_typing: false
type_checker: pyright
